functionsDirectory = "D:\\Desktop\\prueba tecnica\\inmobiliaria\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
headersOrigin = "inline"
plugins = []

[build]
publish = "D:\\Desktop\\prueba tecnica\\inmobiliaria\\netlify"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "D:\\Desktop\\prueba tecnica\\inmobiliaria\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[images]
remote_images = []

[functions]

[functions."*"]

[[headers]]
for = "/_astro/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/.netlify/functions/render"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]