image: node:20

stages:
  - build
  - deploy

variables:
  AZURE_RESOURCE_GROUP: "inmobiliaria_project"
  AZURE_APP_NAME: "inmobiliariafront"
  NODE_ENV: production

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @azure/cli

build:
  stage: build
  script:
    - npm install
    - echo "PUBLIC_API_URL=$PUBLIC_API_URL" > .env.production
    - npm run build

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Logging in to Azure..."
    - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
    - az account set --subscription "$AZURE_SUBSCRIPTION_ID"
    - echo "Deploying to Azure Web App..."
    - zip -r app.zip . -x "node_modules/*"
    - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_NAME --src-path app.zip --type zip
