[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "netlify"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200
